# Generated by Django 5.2.10 on 2026-01-18 19:47

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PiholeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Primary Pi-hole', max_length=100)),
                ('pihole_url', models.URLField(help_text='e.g., https://192.168.1.100')),
                ('password', encrypted_model_fields.fields.EncryptedCharField()),
                ('verify_ssl', models.BooleanField(default=False, help_text='Disable for self-signed certs')),
                ('backup_frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10)),
                ('backup_time', models.TimeField(default='03:00', help_text='Time for daily/weekly backups')),
                ('backup_day', models.SmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, help_text='Day for weekly backups')),
                ('max_backups', models.PositiveIntegerField(default=10, help_text='Maximum number of backups to keep')),
                ('max_age_days', models.PositiveIntegerField(default=30, help_text='Delete backups older than this')),
                ('is_active', models.BooleanField(default=True, help_text='Enable scheduled backups')),
                ('last_successful_backup', models.DateTimeField(blank=True, null=True)),
                ('last_backup_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pi-hole Configuration',
                'verbose_name_plural': 'Pi-hole Configurations',
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('is_manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='backup.piholeconfig')),
            ],
            options={
                'verbose_name': 'Backup Record',
                'verbose_name_plural': 'Backup Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
