# Generated by Django 5.2.10 on 2026-04-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backup", "0002_remove_credential_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="piholeconfig",
            name="env_prefix",
            field=models.CharField(
                default="PRIMARY",
                help_text="Environment variable prefix for credentials (e.g., PRIMARY → PIHOLE_PRIMARY_URL)",
                max_length=50,
                unique=True,
            ),
        ),
    ]
