# Generated by Django 5.2.10 on 2026-04-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_add_multi_instance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='piholeconfig',
            name='connection_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='piholeconfig',
            name='connection_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('ok', 'Connected'), ('auth_error', 'Authentication Error'), ('unreachable', 'Unreachable'), ('not_configured', 'Not Configured'), ('removed', 'Removed')], default='unknown', max_length=20),
        ),
    ]
