# Generated by Django 5.2.10 on 2026-04-09 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0004_add_connection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piholeconfig',
            name='env_prefix',
            field=models.CharField(default='PRIMARY', help_text='Environment variable prefix (e.g., PRIMARY reads PIHOLE_PRIMARY_URL)', max_length=50, validators=[django.core.validators.RegexValidator(message='Prefix must start with a letter and contain only uppercase letters, numbers, and underscores.', regex='^[A-Z][A-Z0-9_]*$')]),
        ),
    ]
